### ISSUE TITLE
Testing PR's and stuff

### ISSUE THREAD

**Issue by moshmage** [bepronetwork/bepro-js-edge#428]
Testing PR's and stuff

**Comment by rodrigosous-a** [comment]
![logo 500](https://user-images.githubusercontent.com/89935517/143610655-fc901233-b647-49d9-92ae-89082d464aa2.png)

**Comment by rodrigosous-a** [comment]
[https://www.figma.com/file/yQITClZ8qyxHBDwPk4gHgC/BEPRO-Network?node-id=6947%3A9280](url)

**Comment by moshmage** [comment]
@moshmage is working on this.

**Comment by moshmage** [comment]
@rodrigosous-a is working on this.

**Comment by moshmage** [comment]
@rodrigosous-a, @rodrigosous-a has a solution - [check your issue](https://dev-web-network.herokuapp.com//issue?id=428&repoId=2)

**Comment by moshmage** [comment]
@rodrigosous-a, @moshmage has a solution - [check your issue](https://dev-web-network.herokuapp.com//issue?id=428&repoId=2)
